### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by kjarnet** [C-D-Lewis/fitbit-dev#1]
First of all, thanks for making the awesome Upcoming app 🙌 That was by far what I missed most from my Pebble.

Would you consider adding an open source license to this project? I'd really love to fork it and expand and tweak on some of it's features. I can of course submit pull requests, but I think it could be beneficial to have a separate fork, as the tweaks I'm planning surely wouldn't suite everyone...

**Comment by C-D-Lewis** [comment]
Hi! Yes, I will try and do this soon. It will likely be the common MIT license which let's you reuse the code with a link back to here.

**Comment by C-D-Lewis** [comment]
Added the Apache License (far too late, sorry!)
